### ISSUE TITLE
"Permission denied"?

### ISSUE THREAD

**Issue by hamelcubsfan** [z0m31en7/Uscrapper#1]
gitpod ~ $ git clone https://github.com/z0m31en7/Uscrapper.git
Cloning into 'Uscrapper'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 43 (delta 15), reused 26 (delta 7), pack-reused 0
Receiving objects: 100% (43/43), 63.03 KiB | 4.20 MiB/s, done.
Resolving deltas: 100% (15/15), done.
gitpod ~ $ cd Uscrapper/install/ && ./install.sh    
bash: ./install.sh: Permission denied

Same "Permissions Denied" in other terminals, too.

**Comment by Blue-osintguy** [comment]
I have the same issue. Also permission denied.

**Comment by z0m31en7** [comment]
To execute any file in *nix based environments, it must be having an executable permission, which can be provided by `chmod +x ./install.sh` which was the issue here, I've updated the steps for installation in README.md. Please refer to the updated guide. Thank you.
