### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by ocervell** [z0m31en7/Uscrapper#12]
Please consider making the tool installable via `pipx install uscrapper`, which means publishing a release to PyPI. I can help if you need help with packaging.

Currently the official `./install.sh` script doesn't install everything needed (you need to run `pip install pyvirtualdisplay` afterwards, and the `chmod +x` doesn't work: `chmod: cannot access '../Uscrapper-v2.0.py': No such file or directory` because `../Uscrapper-v2.0.py` is now `../Uscrapper-vanta.py`.

Thanks for the tool !

**Comment by z0m31en7** [comment]
Hey @ocervell, thank you for pointing that out. I've fixed the current issues, but I would really appreciate a pull request implementing the installation method you suggested.
