### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kinghacker0** [z0m31en7/Uscrapper#14]
┌──(kali㉿kali)-[~/Desktop/Uscrapper]
└─$ python Uscrapper-vanta.py 
Traceback (most recent call last):
  File "/home/kali/Desktop/Uscrapper/Uscrapper-vanta.py", line 13, in <module>
    from webdriver_manager.firefox import GeckoDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by z0m31en7** [comment]
Hey!! Can you confirm that you executed install.sh prior running the Uscrapper-vanta.py?

**Comment by z0m31en7** [comment]
Hey!! Can you confirm that you executed install.sh prior running the Uscrapper-vanta.py? If yes can you send me the output?

**Comment by z0m31en7** [comment]
Thank you for reporting this issue. After thoroughly reviewing and testing the scenario, we have verified that there are no issues or bugs related to this. Everything appears to be functioning as expected.

If you encounter any further problems or have additional concerns, please feel free to reopen this issue or create a new one.

Thanks again for your contribution!
